# Generated by Django 6.0.8 on 2026-09-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_churchevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='worship_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, help_text="The church's main day of worship."),
        ),
    ]
