# Generated by Django 6.0.8 on 2026-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_resource_resourcebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='church',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='church',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='church',
            name='footer_verse',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
