# Generated by Django 6.0.8 on 2026-09-27 12:40

from datetime import timedelta
from django.utils import timezone
from django.db import migrations, models


def backfill_announcement_dates(apps, schema_editor):
    """Give any null-dated announcements a reasonable window."""
    Announcement = apps.get_model("church", "Announcement")
    today = timezone.localdate()
    for announcement in Announcement.objects.all():
        changed = False
        if announcement.start_date is None:
            announcement.start_date = today
            changed = True
        if announcement.end_date is None:
            announcement.end_date = today + timedelta(days=30)
            changed = True
        if changed:
            announcement.save()


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_church_footer_fields'),
    ]

    operations = [
        migrations.RunPython(
            backfill_announcement_dates, migrations.RunPython.noop
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-start_date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AddField(
            model_name='membership',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(default=timezone.now),
            preserve_default=False,
        ),
    ]
