# Generated by Django 6.0.8 on 2026-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_request_end_date_request_start_date_departmentmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='approved_text',
            field=models.TextField(blank=True, help_text="The coordinator's reworded version, used to create the Announcement on approval."),
        ),
    ]
