# Generated by Django 6.0.8 on 2026-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_request_approved_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requested_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='requested_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('schedule', 'Add to schedule')], max_length=20),
        ),
    ]
