#!/bin/bash

# Round 4b, script 2b of 3.

# Applies the admin_views.py patch via a base64-encoded Python script.

# Base64 is used because plain-text heredocs lose indentation in transit.

# Run from ~/harpr AFTER running ./r4b_2_setup.sh.

set -e
cd ~/harpr

echo "=== Decoding patch_views.py from base64 ==="
cat > /tmp/patch_views.b64 << 'ENDB64'
IiIiU3RhbmRhbG9uZSBwYXRjaCBzY3JpcHQgZm9yIGFkbWluX3ZpZXdzLnB5LgpSZXBsYWNlcyBhZG1pbl9kYXNoYm9hcmQgd2l0aCB0aGUgU3VuZGF5LWZpcnN0IHZlcnNpb24gYW5kIGFkZHMgdHdvIG1lbWJlciBndWFyZHMuIFJ1biBvbmNlIGZyb20gfi9oYXJwci4KIiIiCgpmcm9tIHBhdGhsaWIgaW1wb3J0IFBhdGgKCnBhdGggPSBQYXRoKCJjaHVyY2gvdmlld3MvYWRtaW5fdmlld3MucHkiKQp0ZXh0ID0gcGF0aC5yZWFkX3RleHQoKQoKIyAtLS0gRml4IDE6IHJlcGxhY2UgYWRtaW5fZGFzaGJvYXJkIC0tLQpzdGFydF9tYXJrZXIgPSAiQGFkbWluX3JlcXVpcmVkXG5kZWYgYWRtaW5fZGFzaGJvYXJkKHJlcXVlc3QpOiIKZW5kX21hcmtlciA9ICJcblxuQGFkbWluX3JlcXVpcmVkXG5kZWYgc2VydmljZV9saXN0KHJlcXVlc3QpOiIKCnN0YXJ0X2lkeCA9IHRleHQuZmluZChzdGFydF9tYXJrZXIpCmVuZF9pZHggPSB0ZXh0LmZpbmQoZW5kX21hcmtlcikKCmlmIHN0YXJ0X2lkeCA9PSAtMSBvciBlbmRfaWR4ID09IC0xOgogICAgcmFpc2UgU3lzdGVtRXhpdCgiQ291bGQgbm90IGxvY2F0ZSBhZG1pbl9kYXNoYm9hcmQgYmxvY2suIEFib3J0aW5nLiIpCgpuZXdfZGFzaGJvYXJkID0gIiIiQGFkbWluX3JlcXVpcmVkCmRlZiBhZG1pbl9kYXNoYm9hcmQocmVxdWVzdCk6CiAgICBmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRlLCB0aW1lZGVsdGEKCiAgICB0b2RheSA9IHRpbWV6b25lLmxvY2FsZGF0ZSgpCiAgICB3ZWVrX3BhcmFtID0gcmVxdWVzdC5HRVQuZ2V0KCJ3ZWVrIikKCiAgICBpZiB3ZWVrX3BhcmFtOgogICAgICAgIHRyeToKICAgICAgICAgICAgcmVmID0gZGF0ZS5mcm9taXNvZm9ybWF0KHdlZWtfcGFyYW0pCiAgICAgICAgZXhjZXB0IChWYWx1ZUVycm9yLCBUeXBlRXJyb3IpOgogICAgICAgICAgICByZWYgPSB0b2RheQogICAgZWxzZToKICAgICAgICByZWYgPSB0b2RheQoKICAgICMgU3VuZGF5LWZpcnN0IHdlZWs6IFN1bmRheS53ZWVrZGF5KCkgPT0gNiwgc28gc2hpZnQgZm9yd2FyZCBieSAxCiAgICBkYXlzX3NpbmNlX3N1bmRheSA9IChyZWYud2Vla2RheSgpICsgMSkgJSA3CiAgICB3ZWVrX3N0YXJ0ID0gcmVmIC0gdGltZWRlbHRhKGRheXM9ZGF5c19zaW5jZV9zdW5kYXkpCiAgICB3ZWVrX2VuZCA9IHdlZWtfc3RhcnQgKyB0aW1lZGVsdGEoZGF5cz02KQoKICAgIHByZXZfd2VlayA9IHdlZWtfc3RhcnQgLSB0aW1lZGVsdGEoZGF5cz03KQogICAgbmV4dF93ZWVrID0gd2Vla19zdGFydCArIHRpbWVkZWx0YShkYXlzPTcpCgogICAgc2VydmljZXMgPSByZXF1ZXN0LmNodXJjaC5zZXJ2aWNlcy5maWx0ZXIoCiAgICAgICAgZGF0ZV9fcmFuZ2U9KHdlZWtfc3RhcnQsIHdlZWtfZW5kKQogICAgKS5wcmVmZXRjaF9yZWxhdGVkKCJpdGVtcyIpCiAgICBldmVudHMgPSByZXF1ZXN0LmNodXJjaC5ldmVudHMuZmlsdGVyKAogICAgICAgIGRhdGVfX3JhbmdlPSh3ZWVrX3N0YXJ0LCB3ZWVrX2VuZCkKICAgICkuc2VsZWN0X3JlbGF0ZWQoInJlc3BvbnNpYmxlX2RlcGFydG1lbnQiKQoKICAgIGRheXMgPSBbXQogICAgZm9yIGRheV9vZmZzZXQgaW4gcmFuZ2UoNyk6CiAgICAgICAgZGF5ID0gd2Vla19zdGFydCArIHRpbWVkZWx0YShkYXlzPWRheV9vZmZzZXQpCiAgICAgICAgZGF5cy5hcHBlbmQoewogICAgICAgICAgICAiZGF0ZSI6IGRheSwKICAgICAgICAgICAgInNlcnZpY2VzIjogW3MgZm9yIHMgaW4gc2VydmljZXMgaWYgcy5kYXRlID09IGRheV0sCiAgICAgICAgICAgICJldmVudHMiOiBbZSBmb3IgZSBpbiBldmVudHMgaWYgZS5kYXRlID09IGRheV0sCiAgICAgICAgfSkKCiAgICByZXR1cm4gcmVuZGVyKHJlcXVlc3QsICJjaHVyY2gvZGFzaGJvYXJkLmh0bWwiLCB7CiAgICAgICAgImNodXJjaCI6IHJlcXVlc3QuY2h1cmNoLAogICAgICAgICJ0b2RheSI6IHRvZGF5LAogICAgICAgICJ3ZWVrX3N0YXJ0Ijogd2Vla19zdGFydCwKICAgICAgICAid2Vla19lbmQiOiB3ZWVrX2VuZCwKICAgICAgICAicHJldl93ZWVrIjogcHJldl93ZWVrLAogICAgICAgICJuZXh0X3dlZWsiOiBuZXh0X3dlZWssCiAgICAgICAgImRheXMiOiBkYXlzLAogICAgICAgICJzZXJ2aWNlX2NvdW50IjogcmVxdWVzdC5jaHVyY2guc2VydmljZXMuZmlsdGVyKAogICAgICAgICAgICBkYXRlX195ZWFyPXRvZGF5LnllYXIsIGRhdGVfX21vbnRoPXRvZGF5Lm1vbnRoCiAgICAgICAgKS5jb3VudCgpLAogICAgICAgICJwZW5kaW5nX3JlcXVlc3RfY291bnQiOiByZXF1ZXN0LmNodXJjaC5yZXF1ZXN0cy5maWx0ZXIoCiAgICAgICAgICAgIHN0YXR1cz0icGVuZGluZyIKICAgICAgICApLmNvdW50KCksCiAgICAgICAgInJlY2VudF9hY3Rpdml0eSI6IHJlcXVlc3QuY2h1cmNoLmxvZ3Muc2VsZWN0X3JlbGF0ZWQoCiAgICAgICAgICAgICJ1c2VyIiwgInNlcnZpY2UiLCAic2VydmljZV9pdGVtIgogICAgICAgIClbOjEwXSwKICAgICAgICAic2VydmljZV90ZW1wbGF0ZXMiOiByZXF1ZXN0LmNodXJjaC5zZXJ2aWNlX3RlbXBsYXRlcy5maWx0ZXIoaXNfYWN0aXZlPVRydWUpLAogICAgICAgICJkZXBhcnRtZW50cyI6IHJlcXVlc3QuY2h1cmNoLmRlcGFydG1lbnRzLmFsbCgpLAogICAgfSkiIiIKCnRleHQgPSB0ZXh0WzpzdGFydF9pZHhdICsgbmV3X2Rhc2hib2FyZCArIHRleHRbZW5kX2lkeDpdCgojIC0tLSBGaXggMjogR3VhcmQgMSAtLS0Kb2xkX2d1YXJkXzEgPSAoCiAgICAiZGVmIG1lbWJlcl9kZWFjdGl2YXRlKHJlcXVlc3QsIHBrKTpcbiIKICAgICIgICAgbWVtYmVyc2hpcCA9IGdldF9vYmplY3Rfb3JfNDA0KHJlcXVlc3QuY2h1cmNoLm1lbWJlcnNoaXBzLCBwaz1waylcbiIKICAgICIgICAgbWVtYmVyc2hpcC5pc19hY3RpdmUgPSBGYWxzZSIKKQpuZXdfZ3VhcmRfMSA9ICgKICAgICJkZWYgbWVtYmVyX2RlYWN0aXZhdGUocmVxdWVzdCwgcGspOlxuIgogICAgIiAgICBtZW1iZXJzaGlwID0gZ2V0X29iamVjdF9vcl80MDQocmVxdWVzdC5jaHVyY2gubWVtYmVyc2hpcHMsIHBrPXBrKVxuIgogICAgIiAgICBpZiBtZW1iZXJzaGlwLnVzZXIgPT0gcmVxdWVzdC51c2VyOlxuIgogICAgIiAgICAgICAgbWVzc2FnZXMuZXJyb3IocmVxdWVzdCwgXCJZb3UgY2Fubm90IGRlYWN0aXZhdGUgeW91ciBvd24gYWNjb3VudC5cIilcbiIKICAgICIgICAgICAgIHJldHVybiByZWRpcmVjdChcIm1lbWJlcl9saXN0XCIpXG4iCiAgICAiICAgIG1lbWJlcnNoaXAuaXNfYWN0aXZlID0gRmFsc2UiCikKCmlmIG9sZF9ndWFyZF8xIG5vdCBpbiB0ZXh0OgogICAgcmFpc2UgU3lzdGVtRXhpdCgiR3VhcmQgMSB0YXJnZXQgbm90IGZvdW5kLiBBYm9ydGluZy4iKQp0ZXh0ID0gdGV4dC5yZXBsYWNlKG9sZF9ndWFyZF8xLCBuZXdfZ3VhcmRfMSwgMSkKCiMgLS0tIEZpeCAzOiBHdWFyZCAyIC0tLQpvbGRfZ3VhcmRfMiA9ICgKICAgICIgICAgaWYgcmVxdWVzdC5tZXRob2QgPT0gXCJQT1NUXCIgYW5kIGZvcm0uaXNfdmFsaWQoKTpcbiIKICAgICIgICAgICAgIGRhdGEgPSBmb3JtLmNsZWFuZWRfZGF0YVxuIgogICAgIiAgICAgICAgbWVtYmVyc2hpcC5yb2xlID0gZGF0YVtcInJvbGVcIl0iCikKbmV3X2d1YXJkXzIgPSAoCiAgICAiICAgIGlmIHJlcXVlc3QubWV0aG9kID09IFwiUE9TVFwiIGFuZCBmb3JtLmlzX3ZhbGlkKCk6XG4iCiAgICAiICAgICAgICBkYXRhID0gZm9ybS5jbGVhbmVkX2RhdGFcbiIKICAgICIgICAgICAgIGlmIG1lbWJlcnNoaXAudXNlciA9PSByZXF1ZXN0LnVzZXIgYW5kIGRhdGFbXCJyb2xlXCJdICE9IFwiYWRtaW5cIjpcbiIKICAgICIgICAgICAgICAgICBtZXNzYWdlcy5lcnJvcihyZXF1ZXN0LCBcIllvdSBjYW5ub3QgY2hhbmdlIHlvdXIgb3duIHJvbGUgZnJvbSBBZG1pbmlzdHJhdG9yLlwiKVxuIgogICAgIiAgICAgICAgICAgIHJldHVybiByZWRpcmVjdChcIm1lbWJlcl9saXN0XCIpXG4iCiAgICAiICAgICAgICBtZW1iZXJzaGlwLnJvbGUgPSBkYXRhW1wicm9sZVwiXSIKKQoKaWYgb2xkX2d1YXJkXzIgbm90IGluIHRleHQ6CiAgICByYWlzZSBTeXN0ZW1FeGl0KCJHdWFyZCAyIHRhcmdldCBub3QgZm91bmQuIEFib3J0aW5nLiIpCnRleHQgPSB0ZXh0LnJlcGxhY2Uob2xkX2d1YXJkXzIsIG5ld19ndWFyZF8yLCAxKQoKcGF0aC53cml0ZV90ZXh0KHRleHQpCnByaW50KCJBbGwgdGhyZWUgcGF0Y2hlcyBhcHBsaWVkIHRvIGFkbWluX3ZpZXdzLnB5LiIpCg==
ENDB64

base64 -d /tmp/patch_views.b64 > patch_views.py
rm -f /tmp/patch_views.b64

echo "patch_views.py decoded. Lines: $(wc -l < patch_views.py)"
head -3 patch_views.py

echo ""
echo "=== Applying patch_views.py ==="
python3 patch_views.py

echo ""
echo "=== Verifying patches ==="
echo -n "Guard 1 present: "
grep -c "You cannot deactivate your own account" church/views/admin_views.py
echo -n "Guard 2 present: "
grep -c "You cannot change your own role from Administrator" church/views/admin_views.py
echo -n "Sunday-first present: "
grep -c "days_since_sunday" church/views/admin_views.py
echo -n "Old isocalendar present (should be 0): "
grep -c "isocalendar" church/views/admin_views.py || echo 0

echo ""
echo "=== Syntax check ==="
. .venv/bin/activate
python -m py_compile church/views/admin_views.py && echo "admin_views.py: OK"
python -m py_compile church/management/commands/seed_demo.py && echo "seed_demo.py: OK"

echo ""
echo "=== Django check ==="
python manage.py check

echo ""
echo "=== Running seed_demo ==="
python manage.py seed_demo

echo ""
echo "=== Verifying seed data ==="
python manage.py shell -c "
from church.models import Service, ServiceItem, ChurchEvent, Announcement
print('Total services:', Service.objects.count())
print('Completed services:', Service.objects.filter(status='completed').count())
print('Draft services:', Service.objects.filter(status='draft').count())
print('Service items:', ServiceItem.objects.count())
print('Events:', ChurchEvent.objects.count())
print('Announcements:', Announcement.objects.count())
"

echo ""
echo "=== Tests ==="
python manage.py test church

echo ""
echo "=== Cleaning up ==="
rm -f patch_views.py

echo ""
echo "=== Done. ==="