from django.urls import path

from church.views import (
    accounts,
    admin_views,
    api_views,
    dept_views,
    home as home_views,
    public_views,
    invitation_views,
    signup_views,
)

urlpatterns = [
    path("", home_views.home, name="home"),
    path("terms/", public_views.terms, name="terms"),
    path("privacy/", public_views.privacy, name="privacy"),
    path("dashboard/", admin_views.admin_dashboard, name="admin_dashboard"),
    path("services/", admin_views.service_list, name="service_list"),
    path("services/new/", admin_views.service_create, name="service_create"),
    path("services/<int:pk>/", admin_views.service_detail, name="service_detail"),
    path("services/<int:pk>/delete/",
         admin_views.service_delete, name="service_delete"),
    path("services/<int:pk>/freeze/",
         admin_views.service_freeze, name="service_freeze"),
    path("services/<int:pk>/unfreeze/",
         admin_views.service_unfreeze, name="service_unfreeze"),
    path(
        "services/<int:pk>/items/new/",
        admin_views.service_item_create,
        name="service_item_create",
    ),
    path(
        "services/<int:pk>/items/<int:item_pk>/edit/",
        admin_views.service_item_edit,
        name="service_item_edit",
    ),
    path(
        "services/<int:pk>/items/<int:item_pk>/recalculate/",
        admin_views.service_item_recalculate,
        name="service_item_recalculate",
    ),
    path(
        "services/<int:pk>/items/<int:item_pk>/delete/",
        admin_views.service_item_delete,
        name="service_item_delete",
    ),
    path(
        "services/<int:pk>/items/<int:item_pk>/assignments/new/",
        admin_views.assignment_create,
        name="assignment_create",
    ),
    path("events/new/", admin_views.event_create, name="event_create"),
    path("events/<int:pk>/edit/", admin_views.event_edit, name="event_edit"),
    path("events/<int:pk>/delete/", admin_views.event_delete, name="event_delete"),
    path("requests/", admin_views.request_list, name="request_list"),
    path(
        "requests/<int:pk>/respond/",
        admin_views.request_respond,
        name="request_respond",
    ),
    path(
        "requests/<int:pk>/detail/",
        admin_views.request_detail_json,
        name="request_detail_json",
    ),
    path("departments/", admin_views.department_list, name="department_list"),
    path(
        "departments/new/",
        admin_views.department_create,
        name="department_create",
    ),
    path(
        "departments/<int:pk>/edit/",
        admin_views.department_edit,
        name="department_edit",
    ),
    path(
        "departments/<int:pk>/delete/",
        admin_views.department_delete,
        name="department_delete",
    ),
    path("members/", admin_views.member_list, name="member_list"),
    path("members/invite/", admin_views.member_invite, name="member_invite"),
    path("members/<int:pk>/edit/", admin_views.member_edit, name="member_edit"),
    path("account/delete/", accounts.delete_my_account, name="account_delete"),
    path(
        "members/<int:pk>/deactivate/",
        admin_views.member_deactivate,
        name="member_deactivate",
    ),
    path(
        "members/<int:pk>/reactivate/",
        admin_views.member_reactivate,
        name="member_reactivate",
    ),
    path("announcements/", admin_views.announcement_list, name="announcement_list"),
    path(
        "announcements/new/",
        admin_views.announcement_create,
        name="announcement_create",
    ),
    path(
        "announcements/<int:pk>/edit/",
        admin_views.announcement_edit,
        name="announcement_edit",
    ),
    path(
        "announcements/<int:pk>/pause/",
        admin_views.announcement_pause,
        name="announcement_pause",
    ),
    path(
        "announcements/<int:pk>/delete/",
        admin_views.announcement_delete,
        name="announcement_delete",
    ),
    path("ai-insights/", admin_views.ai_insights, name="ai_insights"),
    path("settings/", admin_views.church_settings, name="church_settings"),
    path("dept/", dept_views.dept_dashboard, name="dept_dashboard"),
    path("dept/items/<int:pk>/", dept_views.dept_item_detail,
         name="dept_item_detail"),
    path(
        "dept/items/<int:pk>/assignments/new/",
        dept_views.dept_assignment_create,
        name="dept_assignment_create",
    ),
    path(
        "dept/requests/new/",
        dept_views.dept_request_create,
        name="dept_request_create",
    ),
    path("dept/requests/", dept_views.dept_request_list, name="dept_request_list"),
    path("api/activity/", api_views.api_activity, name="api_activity"),
    path("api/notifications/", api_views.api_notifications,
         name="api_notifications"),
    path(
        "api/notifications/<int:pk>/read/",
        api_views.api_notification_read,
        name="api_notification_read",
    ),
    path(
        "api/notifications/mark-all-read/",
        api_views.api_notifications_mark_all_read,
        name="api_notifications_mark_all_read",
    ),
    path("c/<slug>/", public_views.public_schedule, name="public_schedule"),
    path(
        "c/<slug>/<int:year>-<int:month>-<int:day>/",
        public_views.public_schedule_date,
        name="public_schedule_date",
    ),
    path("c/<slug>/request/", public_views.public_request, name="public_request"),
    path(
        "c/<slug>/bulletin/<int:year>-<int:month>-<int:day>.pdf",
        public_views.public_bulletin_pdf,
        name="public_bulletin_pdf",
    ),
    path("c/<slug>/qr.png", public_views.church_qr, name="church_qr"),
    path("signup/", signup_views.church_signup, name="church_signup"),
    path("invite/<str:token>/", invitation_views.accept_invitation,
         name="accept_invitation"),
    path(
        "dept/assignments/<int:pk>/delete/",
        dept_views.dept_assignment_delete,
        name="dept_assignment_delete",
    ),
    path("dept/roster/", dept_views.dept_roster, name="dept_roster"),
    path(
        "dept/schedule/<int:pk>/",
        dept_views.dept_service_schedule,
        name="dept_service_schedule",
    ),
    path(
        "dept/event/<int:pk>/",
        dept_views.dept_event_detail,
        name="dept_event_detail",
    ),
    path(
        "dept/requests/<int:pk>/",
        dept_views.dept_request_detail,
        name="dept_request_detail",
    ),
    path(
        "dept/requests/<int:pk>/edit/",
        dept_views.dept_request_edit,
        name="dept_request_edit",
    ),
    path(
        "dept/requests/<int:pk>/delete/",
        dept_views.dept_request_delete,
        name="dept_request_delete",
    ),
]
