import io
from xml.sax.saxutils import escape

from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_bulletin_pdf(service):
    buffer = io.BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
        leftMargin=15 * mm,
        rightMargin=15 * mm,
    )
    styles = getSampleStyleSheet()
    title = ParagraphStyle(
        "ChurchTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=HexColor("#2b2823"),
        spaceAfter=4,
    )
    subtitle = ParagraphStyle(
        "ChurchSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        textColor=HexColor("#6f6a60"),
        spaceAfter=16,
    )
    item_title = ParagraphStyle(
        "ItemTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=HexColor("#2b2823"),
    )
    item_meta = ParagraphStyle(
        "ItemMeta",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        textColor=HexColor("#6f6a60"),
    )

    elements = [
        Paragraph(escape(service.church.name), title),
        Paragraph(
            f"{escape(service.name)} — {service.date.strftime('%A, %d %B %Y')}",
            subtitle,
        ),
    ]
    data = [["Time", "Item", "Department", "Assigned To"]]
    items = service.items.select_related("responsible_department").prefetch_related("assignments").order_by("order")
    for item in items:
        department = item.responsible_department.name if item.responsible_department else "—"
        assignments = ", ".join(
            f"{assignment.person_name} ({assignment.role})"
            for assignment in item.assignments.all()
        ) or "—"
        data.append(
            [
                Paragraph(item.planned_start.strftime("%H:%M"), item_title),
                Paragraph(escape(item.title), item_title),
                Paragraph(escape(department), item_meta),
                Paragraph(escape(assignments), item_meta),
            ]
        )

    table = Table(data, colWidths=[20 * mm, 60 * mm, 40 * mm, 50 * mm])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), HexColor("#eceae3")),
                ("TEXTCOLOR", (0, 0), (-1, 0), HexColor("#2b2823")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#d9d4c6")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
            ]
        )
    )
    elements.append(table)
    announcements = service.announcements.filter(is_active=True, show_on_public=True)
    if announcements:
        elements.append(Spacer(1, 12 * mm))
        elements.append(Paragraph("Announcements", title))
        for announcement in announcements:
            elements.append(
                Paragraph(
                    f"• {escape(announcement.title)}: {escape(announcement.body)}",
                    item_meta,
                )
            )
    elements.append(Spacer(1, 16 * mm))
    elements.append(Paragraph("Generated by Harpr Church", item_meta))
    document.build(elements)
    buffer.seek(0)
    return buffer